sudo: required
services:
  - docker

before_install:
  - docker build -t DineshTraining2020/nodejsTesting -f Dockerfile.dev .

script:
  - docker run DineshTraining2020/nodejsTesting npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-217663208034"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


